name: Azure .NET Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Legg til denne linjen for å gi skrive-tillatelser til ID-token

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.202'  # Erstatt med din .NET-versjoner

    # Steg 3: Logg på Azure med Service Principal
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}  # Legg til Service Principal Client ID i GitHub Secrets
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}  # Legg til Service Principal Client Secret i GitHub Secrets
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}  # Legg til Azure Tenant ID i GitHub Secrets
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Legg til Azure Subscription ID i GitHub Secrets
        auth-type: SERVICE_PRINCIPAL  # Sørg for at dette er riktig (SERVICE_PRINCIPAL)a
    
    - name: Build and publish .NET app
      run: |
        dotnet build
        dotnet publish -c Release -o ./publish

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: csserver
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish
